### ISSUE TITLE
airshare 0.1.6 release failed to build with py3.12

### ISSUE THREAD

**Issue by chenrui333** [KuroLabs/Airshare#29]
Trying to build 0.1.6 against python 3.12, but ran into the following build failure

```
  running build_ext
  building 'aiohttp._websocket' extension
  creating build/temp.macosx-13-arm64-cpython-312
  creating build/temp.macosx-13-arm64-cpython-312/aiohttp
  clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/Cellar/airshare/0.1.6_6/libexec/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c aiohttp/_websocket.c -o build/temp.macosx-13-arm64-cpython-312/aiohttp/_websocket.o
  aiohttp/_websocket.c:3042:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  aiohttp/_websocket.c:3097:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  aiohttp/_websocket.c:3238:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  aiohttp/_websocket.c:3293:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  aiohttp/_websocket.c:3744:47: error: no member named 'ob_digit' in 'struct _longobject'
      const digit* digits = ((PyLongObject*)b)->ob_digit;
                            ~~~~~~~~~~~~~~~~~~  ^
  5 errors generated.
  error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
  error: subprocess-exited-with-error
```

relates to https://github.com/Homebrew/homebrew-core/pull/150467

**Comment by chenrui333** [comment]
- https://github.com/aio-libs/aiohttp/issues/7675
